= riscv-tools image:https://travis-ci.org/riscv/riscv-tools.svg?branch=master["Build Status",link="https://travis-ci.org/riscv/riscv-tools"]

The RISC-V toolchain is a set of tools for developing software on the
https://riscv.org[RISC-V] instruction set architecture; it consists of
the following components:

.RISC-V toolchain
 * https://github.com/riscv/riscv-fesvr[riscv-fesvr]
    a "front-end" server
 * https://github.com/riscv/riscv-gnu-toolchain[riscv-gnu-toolchain] a RISC-V cross-compiler
     image:https://travis-ci.org/riscv/riscv-gnu-toolchain.svg?branch=master["Build Status",link="https://travis-ci.org/riscv/riscv-gnu-toolchain"]
   - https://github.com/riscv/riscv-binutils-gdb[riscv-binutils-gdb] port of GNU Debugger
   - https://github.com/riscv/riscv-dejagnu[riscv-dejagnu] testing framework
   - https://github.com/riscv/riscv-gcc[riscv-gcc] port of the GNU Compiler Collection
   - https://github.com/riscv/riscv-glibc[riscv-glibc] GNU C Library
   - https://github.com/riscv/riscv-newlib[riscv-newlib] Newlib C Library
 * https://github.com/riscv/riscv-isa-sim[riscv-isa-sim]
    Spike, a RISC-V ISA simulator
 * https://github.com/riscv/riscv-linux[riscv-linux]
    the Linux kernel ported to RISC-V
 * https://github.com/riscv/riscv-llvm[riscv-llvm]
    low lever virtual machine image:https://travis-ci.org/riscv/riscv-llvm.svg?branch=riscv-trunk["Build Status",link="https://travis-ci.org/riscv/riscv-llvm"]
 * https://github.com/riscv/riscv-opcodes[riscv-opcodes]
    the RISC-V opcodes executable by the simulator
 * https://github.com/riscv/riscv-openocd[riscv-openocd]
    onchip programming and debugging image:https://travis-ci.org/riscv/riscv-openocd.svg?branch=riscv["Build Status",link="https://travis-ci.org/riscv/riscv-openocd"]
 * https://github.com/riscv/riscv-pk[riscv-pk]
    a proxy kernel for the RISC-V Newlib port
 * https://github.com/riscv/riscv-tests[riscv-tests]
    a set of assembly tests and benchmarks

'''

To develop with RISC-V, you'll need at least one kernel and a C
library. Currently, there exists

 . the https://github.com/riscv/riscv-newlib/[`riscv-newlib`] library using
the https://github.com/riscv/riscv-pk[`riscv-pk`] proxy kernel and
 . the https://github.com/riscv/riscv-glibc[`riscv-glibc`] library
using the https://github.com/riscv/riscv-linux[`riscv-linux`] kernel.

See the link:doc/FAQ.html[FAQ] for more information about the different
options. If you run into any troubles along your RISC-V journey, check
the link:doc/Troubleshooting.html[Troubleshooting] document and the
https://github.com/riscv/riscv-tools/issues[issues] page on GitHub.


== Dependencies

Ubuntu:

    # apt-get install autoconf automake autotools-dev curl device-tree-compiler libmpc-dev libmpfr-dev libgmp-dev libusb-1.0-0-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev device-tree-compiler pkg-config

Fedora:

    # dnf install autoconf automake @development-tools curl dtc libmpc-devel mpfr-devel gmp-devel gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib-devel

OS X:

    # brew install dtc gawk gnu-sed gmp mpfr libmpc isl wget automake md5sha1sum

NOTE: For OS X, you can also install the tools with
https://github.com/riscv/homebrew-riscv[homebrew-riscv]. This repo will build
with Apple's command-line developer tools (clang) in addition to gcc.


=== C++11 Compiler Support

Building `riscv-tools` requires a compiler with support for C++11 (e.g.,
GCC >= 4.8). To use a compiler different than your system default, export
the `CC` and `CXX` environment variables:

    $ export CC=gcc-4.8 CXX=g++-4.8


== Obtaining the Sources

Clone the `riscv-tools` repository along with all of its submodules:

    $ git clone --recursive https://github.com/riscv/riscv-tools

[NOTE]
====
If you've already cloned the repo but didn't include the
submodules, you can update them all with:

    $ git submodules update --init --recursive

====


== pk/Newlib Installation

The easiest path to RISC-V is to use the `riscv-pk` kernel and the
`riscv-newlib` library.

Run `make` without any arguments to install those tools:

    $ make

NOTE: This will install the tools in the `./install/` directory by
default, to change that set the `RISCV` variable when running make:
`make RISCV=/somewhere/else`.  To see all of the available options, run
`make help`.

[WARNING]
====
In order for your shell to find the tools, the `<RISCV>/bin` subdirectory
must be in your `PATH` environment variable; add the default path with

    $ export PATH=$PATH:${PWD}/install/bin
====


=== Testing Your Toolchain

Let's test our new toolchain on the quintessential "Hello world!" program:

.hello.c
----
#include <stdio.h>
int main(void) {
    printf("Hello world!\n");
    return 0;
}
----

Build it with the cross-compiler:

    $ riscv64-unknown-elf-gcc -o hello hello.c

In order to run this RISC-V binary on our X86 host machine, we need the
RISC-V ISA simulator, `riscv-isa-sim` (a.k.a., `spike`) to run the proxy
kernel which can understand the non-native system calls made by our new
"Hello World!" binary:

    $ spike pk hello

NOTE: The RISC-V architectural simulator, `spike`, takes as its argument the
path of the binary to run. Then, `pk` receives as _its_ argument the
name of the program you want to run.

Now you're all set to develop on the RISC-V instruction set architecture
with `riscv-newlib` and `riscv-pk`!


== Linux/Glibc Installation

IMPORTANT: This section is only required for developing RISC-V on the
`riscv-linux` kernel with the `riscv-glibc` library (otherwise, you can
use the `riscv-pk` kernel with the `riscv-newlib` library).

Instead of building all of the tools in the `riscv-tools` set,
we only *need* to build `riscv-fesvr`, `riscv-isa-sim` and the
`riscv-gnu-toolchain` (configured for `riscv-linux`).

In addition, this will download https://www.busybox.net[BusyBox] to give
us a set of basic utilities once we've booted the Linux kernel.

You can do all of this with `make`:

TIP: If you want to speed up the process, you can pass the `-j[number]`
option to use `[number]` threads.

    $ make -j4 linux


The `linux` argument builds `riscv64-unknown-linux-gnu-gcc` (the
cross-compiler used to build binaries linked to `riscv-glibc`), a
`busybox` binary (`bbl`), and a compiled Linux kernel (`vmlinux`).

Invoke `spike` to use the `bbl` binary to run the `vmlinux` compiled Linux
kernel.

    $ spike bbl vmlinux

If there are no problems, an `ash` prompt will appear after the boot
process completes. It will be pretty useless without the usual plethora
of command-line utilities, but you can add them as BusyBox applets. Have
fun and report back!

NOTE: To exit the simulator, kill the process with `Ctrl-c`.


[bibliography]
== References

- Waterman, A., Lee, Y., Patterson, D., and Asanovic, K,. "The RISC-V
Instruction Set Manual," vol. II,
https://inst.eecs.berkeley.edu/~cs152/sp12/handouts/riscv-supervisor.pdf,
2012.
- Bovet, D.P., and Cesati, M. _Understanding the Linux Kernel_, 3rd ed.,
O'Reilly, 2006.
- Gorman, M. _Understanding the Linux Virtual Memory Manager_,
http://www.csn.ul.ie/~mel/docs/vm/guide/pdf/understand.pdf, 2003.
- Corbet, J., Rubini, A., and Kroah-Hartman, G. _Linux Device Drivers_,
3rd ed., O'Reilly, 2005.
- Beekmans, G. _Linux From Scratch_, version 7.3,
http://www.linuxfromscratch.org/lfs/view/stable/, 2013.
- This document is based on one originally authored by
https://ocf.berkeley.edu/~qmn[Quan Nguyen] and is available, in two
parts, at https://ocf.berkeley.edu/~qmn/linux/install-newlib.html and
https://ocf.berkeley.edu/~qmn/linux/install.html; updates were also
made by Sagar Karandikar.

